# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(verbose_name='start date time')),
                ('end_time', models.DateTimeField(verbose_name='end date time')),
                ('average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('highest_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lowest_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('first_quartile', models.DecimalField(decimal_places=2, max_digits=5)),
                ('median', models.DecimalField(decimal_places=2, max_digits=5)),
                ('third_quartile', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiaodaschool.Examine')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_gender', models.IntegerField(choices=[(0, 'Boy'), (1, 'Girl'), (255, 'Unknown')], default=255)),
                ('stu_category', models.IntegerField(default=255)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiaodaschool.Student'),
        ),
    ]
